{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "data = pd.read_csv('keyword.csv')['indikasi']\n",
    "data.index += 1\n",
    "# data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "tfidf = TfidfVectorizer()\n",
    "wordSet = []\n",
    "for each in data:\n",
    "    for ieach in each.split():\n",
    "        if ieach not in wordSet:\n",
    "            wordSet.append(ieach)\n",
    "wordSet = set(wordSet)\n",
    "\n",
    "data_new = []\n",
    "wordDict = [None] * len(data)\n",
    "for row in enumerate(data):\n",
    "    wordDict[row[0]] = dict.fromkeys(wordSet, 0)\n",
    "    for word in row[1].split():\n",
    "        wordDict[row[0]][word]+=1\n",
    "    data_new.append(wordDict[row[0]])\n",
    "\n",
    "# pd.DataFrame(data_new)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def computeTF(wordDict, bow):\n",
    "    tfDict = {}\n",
    "    bowCount = len(bow)\n",
    "    for word, count in wordDict.items():\n",
    "        tfDict[word] = count/float(bowCount)\n",
    "    return tfDict\n",
    "\n",
    "tfData = [None] * len(data)\n",
    "for row in enumerate(data):\n",
    "    tfData[row[0]] = computeTF(wordDict[row[0]], row[1])\n",
    "\n",
    "def computeIDF(docList):\n",
    "    import math\n",
    "    idfDict = {}\n",
    "    N = len(docList)\n",
    "    \n",
    "    idfDict = dict.fromkeys(docList[0].keys(), 0)\n",
    "    for doc in docList:\n",
    "        for word, val in doc.items():\n",
    "            if val > 0:\n",
    "                idfDict[word] += 1\n",
    "    \n",
    "    for word, val in idfDict.items():\n",
    "        idfDict[word] = math.log10(N / float(val))\n",
    "        \n",
    "    return idfDict\n",
    "\n",
    "idfs = computeIDF(data_new)\n",
    "\n",
    "def computeTFIDF(tfBow, idfs):\n",
    "    tfidf = {}\n",
    "    for word, val in tfBow.items():\n",
    "        tfidf[word] = val*idfs[word]\n",
    "    return tfidf\n",
    "\n",
    "tfidfBow = [None] * len(data)\n",
    "bow_new = []\n",
    "for each in enumerate(data):\n",
    "    tfidfBow[each[0]] = computeTFIDF(tfData[each[0]], idfs)\n",
    "    bow_new.append(tfidfBow[each[0]])\n",
    "indexed = pd.DataFrame(bow_new)\n",
    "# indexed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['4', '5', '6', '13']"
      ]
     },
     "execution_count": 127,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "searching = \"lesu dan tidak bergairah\"\n",
    "searching = [s.lower() for s in searching.split()]\n",
    "index = indexed[searching].sum(axis = 1, skipna = True)\n",
    "index = pd.DataFrame(index.sort_values(ascending=False), columns=['index rate'])\n",
    "index.index += 1\n",
    "\n",
    "allData = pd.DataFrame(data)\n",
    "final_table = index.join(allData)\n",
    "indikasi = final_table[final_table['index rate'] > 0.0].index.values.tolist()\n",
    "indikasi = [str(i) for i in indikasi]\n",
    "indikasi\n",
    "# final_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>indikasi</th>\n",
       "      <th>value</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>md2</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>keracunan stapylococcus aureus</td>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>keracunan jamur beracun</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>keracunan salmonellae</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>keracunan clostridium botulinum</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>keracunan campylobacter</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                            indikasi  value\n",
       "md2                                        \n",
       "33    keracunan stapylococcus aureus      7\n",
       "34           keracunan jamur beracun      6\n",
       "35             keracunan salmonellae      9\n",
       "36   keracunan clostridium botulinum      5\n",
       "37           keracunan campylobacter      5"
      ]
     },
     "execution_count": 121,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inner Product\n",
    "metadata1 = pd.read_csv('metadata1.csv').set_index('md1')\n",
    "result1 = metadata1[indikasi].sum(axis = 1, skipna = True)\n",
    "\n",
    "metadata2 = pd.read_csv('metadata2.csv').set_index('md2')\n",
    "value1 = result1.values.tolist()\n",
    "\n",
    "innerProductresult = pd.DataFrame((metadata2 * value1).sum(axis = 1, skipna = True), columns={'value'})\n",
    "# innerProductResult = innerProductresult.join(data)[['indikasi','value']]\n",
    "\n",
    "highestInnerProductRate = (metadata2 * value1).sum(axis = 1, skipna = True).idxmax()\n",
    "data[highestInnerProductRate]\n",
    "innerProductResult\n",
    "# value1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>indikasi</th>\n",
       "      <th>value</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>md2</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>keracunan stapylococcus aureus</td>\n",
       "      <td>0.602665</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>keracunan jamur beracun</td>\n",
       "      <td>0.516035</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>keracunan salmonellae</td>\n",
       "      <td>0.676533</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>keracunan clostridium botulinum</td>\n",
       "      <td>0.609462</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>keracunan campylobacter</td>\n",
       "      <td>0.436427</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                            indikasi     value\n",
       "md2                                           \n",
       "33    keracunan stapylococcus aureus  0.602665\n",
       "34           keracunan jamur beracun  0.516035\n",
       "35             keracunan salmonellae  0.676533\n",
       "36   keracunan clostridium botulinum  0.609462\n",
       "37           keracunan campylobacter  0.436427"
      ]
     },
     "execution_count": 128,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Cosine Similarity\n",
    "# indikasi = ['1','2','4','5','6','8','9','11']\n",
    "metadata1 = pd.read_csv('metadata1.csv').set_index('md1')\n",
    "xy = metadata1[indikasi].sum(axis = 1, skipna = True)\n",
    "y2 = metadata1.sum(axis = 1, skipna = True)**(1/2)\n",
    "x2 = len(indikasi)**(1/2)\n",
    "result1 = xy/(x2*y2)\n",
    "result1\n",
    "\n",
    "metadata2 = pd.read_csv('metadata2.csv').set_index('md2')\n",
    "\n",
    "x22 = math.sqrt((result1**2).sum())\n",
    "y22 = metadata2.sum(axis = 1, skipna = True)**(1/2)\n",
    "result1 = result1.values.tolist()\n",
    "xy2 = (metadata2 * result1).sum(axis = 1, skipna = True)\n",
    "# xy2 = pd.DataFrame((metadata2 * result1).sum(axis = 1, skipna = True), columns={'value'})\n",
    "pd.DataFrame(xy2/(x22*y22), columns={'value'}).join(data)[['indikasi','value']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
